#!/usr/bin/env python3

import argparse
import json
import re


PARAM_RE = re.compile(r"\.(?P<name>[A-Za-z0-9_]+)\((?P<value>[^)]+)\)")
PORT_RE = re.compile(r"\.(?P<name>[A-Za-z0-9_]+)\((?P<value>[^)]+)\)")
START_RE = re.compile(r"^\s*(?P<module>abr_1r1w(?:_be)?_ram)\s*#\(")
INST_RE = re.compile(r"^\s*\)\s+(?P<inst>\\[^ ]+|[A-Za-z0-9_.$]+)\s+\(")


def parse_int(expr):
    expr = expr.strip()
    m = re.match(r"\d+'s?d(\d+)$", expr)
    if m:
        return int(m.group(1))
    m = re.match(r"\d+'h([0-9a-fA-F]+)$", expr)
    if m:
        return int(m.group(1), 16)
    return int(expr, 0)


def clean_name(s):
    s = s.strip()
    if s.startswith("\\"):
        s = s[1:]
    return s.strip()


def parse_instances(lines):
    out = []
    i = 0
    while i < len(lines):
        m = START_RE.match(lines[i])
        if not m:
            i += 1
            continue

        module = m.group("module")
        block = [lines[i]]
        i += 1
        while i < len(lines):
            block.append(lines[i])
            if lines[i].strip() == ");":
                break
            i += 1

        text = "".join(block)
        params = {}
        ports = {}
        in_ports = False
        inst = None
        for line in block:
            im = INST_RE.match(line)
            if im:
                inst = clean_name(im.group("inst"))
                in_ports = True
                continue
            for pm in PARAM_RE.finditer(line):
                if in_ports:
                    ports[pm.group("name")] = clean_name(pm.group("value"))
                else:
                    params[pm.group("name")] = parse_int(pm.group("value"))

        if inst is None:
            raise ValueError("could not parse SRAM instance from block:\n" + text)

        data_width = params["DATA_WIDTH"]
        depth = params["DEPTH"]
        out.append({
            "module": module,
            "instance": inst,
            "byte_enable": module == "abr_1r1w_be_ram",
            "depth": depth,
            "data_width": data_width,
            "addr_width": (depth - 1).bit_length(),
            "ports": ports,
        })
        i += 1
    return out


def c_ident(name):
    out = []
    for ch in name:
        if ch.isalnum():
            out.append(ch)
        else:
            out.append("_")
    s = "".join(out).strip("_")
    if not s or s[0].isdigit():
        s = "sram_" + s
    return s


def write_header(path, srams):
    with open(path, "w", encoding="utf-8") as f:
        f.write("/* Generated by extract_sram_meta.py. */\n")
        f.write("#ifndef PRESI_ABR_SRAM_MAP_H\n")
        f.write("#define PRESI_ABR_SRAM_MAP_H\n\n")
        f.write("#define PRESI_ABR_SRAM_COUNT %d\n\n" % len(srams))
        f.write("struct presi_sram_desc {\n")
        f.write("    const char *name;\n")
        f.write("    unsigned depth;\n")
        f.write("    unsigned data_width;\n")
        f.write("    unsigned addr_width;\n")
        f.write("    unsigned byte_enable;\n")
        f.write("};\n\n")
        f.write("static const struct presi_sram_desc presi_sram_descs[] = {\n")
        for sram in srams:
            f.write("    { \"%s\", %u, %u, %u, %u },\n" % (
                sram["instance"], sram["depth"], sram["data_width"],
                sram["addr_width"], 1 if sram["byte_enable"] else 0))
        f.write("};\n\n")
        for idx, sram in enumerate(srams):
            f.write("#define PRESI_SRAM_%s %d\n" % (
                c_ident(sram["instance"]).upper(), idx))
        f.write("\n#endif\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--netlist", required=True)
    ap.add_argument("--json", required=True)
    ap.add_argument("--header", required=True)
    args = ap.parse_args()

    with open(args.netlist, "r", encoding="utf-8") as f:
        srams = parse_instances(f.readlines())

    with open(args.json, "w", encoding="utf-8") as f:
        json.dump({"srams": srams}, f, indent=2)
        f.write("\n")

    write_header(args.header, srams)
    print("sram-meta: %d SRAM instances" % len(srams))


if __name__ == "__main__":
    main()
