#!/usr/bin/env python3

import argparse


def cname(name):
    if name == "0s":
        return "PRESI_0"
    if name == "1s":
        return "PRESI_1"

    out = []
    for ch in name:
        if ch.isalnum():
            out.append(ch)
        else:
            out.append("_")
    s = "".join(out).strip("_")
    if not s:
        s = "unnamed"
    if s[0].isdigit():
        s = "n_" + s
    return s


class NameMap:
    def __init__(self):
        self.names = {}
        self.order = []

    def ref(self, name):
        if name in ("0s", "1s"):
            return cname(name)
        if name not in self.names:
            c = cname(name)
            base = c
            i = 1
            while c in self.order:
                c = "%s_%d" % (base, i)
                i += 1
            self.names[name] = c
            self.order.append(c)
        return self.names[name]


def parse_instance(line):
    fields = line.split()
    if len(fields) < 2 or not fields[0].startswith("X"):
        return None
    return fields


def translate(spice_file, var_file, clk_file, map_file):
    names = NameMap()
    lines = []
    flops = set()
    delay_count = 0

    with open(spice_file, "r", encoding="utf-8") as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.strip()
            if not line or line.startswith("*") or line.startswith("."):
                continue
            fields = parse_instance(line)
            if fields is None:
                if line.startswith("V"):
                    fields = line.split()
                    if len(fields) >= 4 and fields[3] == "DC":
                        dst = names.ref(fields[2])
                        src = names.ref(fields[1])
                        lines.append("%s = %s;" % (dst, src))
                        continue
                raise SystemExit("%s:%d: unsupported SPICE line: %s" %
                                 (spice_file, lineno, raw.rstrip()))

            gate = fields[-1]
            pins = fields[1:-1]
            if gate == "BUF" and len(pins) == 2:
                lines.append("%s = %s;" % (names.ref(pins[1]),
                                           names.ref(pins[0])))
            elif gate == "NOT" and len(pins) == 2:
                lines.append("%s = ~%s;" % (names.ref(pins[1]),
                                            names.ref(pins[0])))
            elif gate == "NAND" and len(pins) == 3:
                lines.append("%s = ~(%s & %s);" %
                             (names.ref(pins[2]), names.ref(pins[0]),
                              names.ref(pins[1])))
            elif gate == "NOR" and len(pins) == 3:
                lines.append("%s = ~(%s | %s);" %
                             (names.ref(pins[2]), names.ref(pins[0]),
                              names.ref(pins[1])))
            elif gate == "DFF" and len(pins) == 3:
                clk, d, q = pins
                qref = names.ref(q)
                dref = names.ref(d)
                if d in flops:
                    delay = "_presi_delay_%u" % delay_count
                    delay_count += 1
                    names.order.append(delay)
                    lines.append("%s = %s; %s = %s;" %
                                 (qref, delay, delay, dref))
                else:
                    lines.append("%s = %s;" % (qref, dref))
                flops.add(q)
                names.ref(clk)
            elif gate == "DFFSR" and len(pins) == 5:
                clk, d, q, s, r = pins
                qref = names.ref(q)
                lines.append("if (%s & 1) %s = PRESI_1; "
                             "else if (%s & 1) %s = PRESI_0; "
                             "else %s = %s;" %
                             (names.ref(s), qref, names.ref(r), qref,
                              qref, names.ref(d)))
                flops.add(q)
                names.ref(clk)
            else:
                raise SystemExit("%s:%d: unsupported gate %s with %d pins" %
                                 (spice_file, lineno, gate, len(pins)))

    with open(var_file, "w", encoding="utf-8") as f:
        f.write("/* Generated by spice_to_c.py. */\n")
        for c in sorted(names.order):
            if c not in ("PRESI_0", "PRESI_1"):
                f.write("static presi_t %s;\n" % c)

    with open(clk_file, "w", encoding="utf-8") as f:
        f.write("/* Generated by spice_to_c.py. */\n")
        for line in lines:
            f.write("%s\n" % line)

    with open(map_file, "w", encoding="utf-8") as f:
        f.write("spice_name,c_name\n")
        for spice_name, c_name in sorted(names.names.items()):
            f.write("%s,%s\n" % (spice_name, c_name))

    print("translated %d gate statements, %d variables" %
          (len(lines), len(names.order)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--spice", required=True)
    ap.add_argument("--vars", required=True)
    ap.add_argument("--clock", required=True)
    ap.add_argument("--map", required=True)
    args = ap.parse_args()
    translate(args.spice, args.vars, args.clock, args.map)


if __name__ == "__main__":
    main()
